"""first migration

Revision ID: 2134201d9799
Revises: 
Create Date: 2026-01-19 20:47:02.365752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2134201d9799'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chercheurs',
    sa.Column('id_chercheur', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('specialite', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('id_lab', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_lab'], ['laboratoires.id_lab'], ),
    sa.PrimaryKeyConstraint('id_chercheur'),
    sa.UniqueConstraint('email')
    )
    op.create_table('laboratoires',
    sa.Column('id_lab', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=False),
    sa.Column('domaine', sa.String(length=100), nullable=False),
    sa.Column('university', sa.String(length=150), nullable=False),
    sa.Column('directeur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['directeur_id'], ['chercheurs.id_chercheur'], ),
    sa.PrimaryKeyConstraint('id_lab')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laboratoires')
    op.drop_table('chercheurs')
    # ### end Alembic commands ###
