"""empty message

Revision ID: 9368bb4ab107
Revises: 
Create Date: 2026-01-24 19:10:06.241177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9368bb4ab107'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chercheurs',
    sa.Column('id_chercheur', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('specialite', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('id_lab', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_lab'], ['laboratoires.id_lab'], ),
    sa.PrimaryKeyConstraint('id_chercheur'),
    sa.UniqueConstraint('email')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratoires',
    sa.Column('id_lab', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=False),
    sa.Column('domaine', sa.String(length=100), nullable=False),
    sa.Column('university', sa.String(length=150), nullable=False),
    sa.Column('directeur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['directeur_id'], ['chercheurs.id_chercheur'], ),
    sa.PrimaryKeyConstraint('id_lab')
    )
    op.create_table('experience_chercheur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_experience', sa.Integer(), nullable=False),
    sa.Column('id_chercheur', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chercheur'], ['chercheurs.id_chercheur'], ),
    sa.ForeignKeyConstraint(['id_experience'], ['experience.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('type_parametre', sa.String(), nullable=False),
    sa.Column('id_experience', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_experience'], ['experience.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mesure')
    op.drop_table('experience_chercheur')
    op.drop_table('laboratoires')
    op.drop_table('experience')
    op.drop_table('chercheurs')
    # ### end Alembic commands ###
