"""first migration2

Revision ID: c93109cac537
Revises: 2134201d9799
Create Date: 2026-01-19 21:25:37.728213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93109cac537'
down_revision = '2134201d9799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('descritption', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience_chercheur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_experience', sa.Integer(), nullable=False),
    sa.Column('id_chercheur', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chercheur'], ['chercheurs.id_chercheur'], ),
    sa.ForeignKeyConstraint(['id_experience'], ['experience.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience_chercheur')
    op.drop_table('experience')
    # ### end Alembic commands ###
